spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9096

inventory-url: "http://localhost:9097/api/inventory"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9098/eureka/