spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 0
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:9098/eureka/